### ISSUE TITLE
Websocket Life

### ISSUE THREAD

**Issue by ThePrivatePanda** [Sxvxgee/DankCord#27]
Websocket disconnects after a duration, could be 5 minutes, could be 4 hours- NOT caused by machine/host network.

no useful tracebacks, more information on this issue is required.

**Comment by skifli** [comment]
Probably discord requesting reconnect (opcode 7)? Documented as happening randomly, whenever discord feels like it. For reconnecting, the session ID and last received sequence ID need to be sent when reconnecting

**Comment by ThePrivatePanda** [comment]
No, that has been handled.

**Comment by ThePrivatePanda** [comment]
Just occurred again and here's the traceback.
```
Exception in thread Thread-1 (heartbeat):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "DankCord/src/DankCord/gateway.py", line 43, in heartbeat
    self.ws.send(orjson.dumps({"op": 1, "d": None}))
  File "DankCord/.env/lib/python3.11/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "DankCord/.env/lib/python3.11/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "DankCord/.env/lib/python3.11/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "DankCord/.env/lib/python3.11/site-packages/websocket/_socket.py", line 143, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by skifli** [comment]
Ok, so its a bit like the reconnect. Here's a pic from the docs.
![image](https://user-images.githubusercontent.com/121291719/212755400-dd2dff96-3d4c-4767-88c3-721fb634d461.png)

**Comment by skifli** [comment]
You just gotta handle it like a new session.

**Comment by ThePrivatePanda** [comment]
That is handled as well. Currently, dankcord yeets the old connection and opens a new one.

**Comment by skifli** [comment]
Well apparently it doesn't? Why is the error saying the connection is closed then?

**Comment by ThePrivatePanda** [comment]
It should raise the exception before, in the receive part (_events_listener). The fact that it waits for heartbeat is more troublesome

**Comment by skifli** [comment]
Hmm, then idk. I don't have that much knowledge of the code.
